### ISSUE TITLE
AttributeError: 'Language' object has no attribute 'dictionary'

### ISSUE THREAD

**Issue by ptrab** [Botmasher/syllables-names-generator#1]
Hi,
when I follow your way on how to install it, etc., I encounter the following problem after initiatin `python -m languagebuilder`:

```
Traceback (most recent call last):
  File "/home/philipp/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/philipp/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/philipp/languages/syllables-names-generator/languagebuilder/__main__.py", line 1, in <module>
    from .example import my_language
  File "/home/philipp/languages/syllables-names-generator/languagebuilder/example.py", line 235, in <module>
    search_results = my_language.dictionary.search(keywords="instrumental")
AttributeError: 'Language' object has no attribute 'dictionary'
```

Do you have any idea on what I might be doing wrong?

Thank you very much for your time!
Philipp

**Comment by Botmasher** [comment]
Hi Philipp,

Thanks for checking. You're doing nothing wrong. Since I've been the creator+user so far, I've been tinkering on the main branch and haven't had a stable version for a while. Once I get it back to a less broken state, I will keep changes in a feature branch to avoid raising such issues.

The last working commit I can identify is `de27a4bac66db229f49671d374731837cee4633b`. After checking that one out, all tests passed. However, running main still errs. If you're still interested in running the example but don't mind a few hacky hassles, these steps work for me:
- `git checkout` that last working commit
- open `example.py`
- replace every instance of `my_language.dictionary` with `my_language.vocabulary`
- comment out or delete the call to `my_language.add_grammar()`
- run `python -m languagebuilder` (or for me `python3`...)

I've been slow to write up any API documentation. I should make time to do that. In the meantime, the examples, `tests/` and docstrings double as a starting point.

-Josh

**Comment by ptrab** [comment]
Hi Josh,

thank you for your help, now it works. :+1:

All the best,
Philipp
